### ISSUE TITLE
Running UI locally fails with JDK 23

### ISSUE THREAD

**Issue by qdubious** [eclipse-ee4j/starter#336]
I'm unable to run the UI locally after following the instructions in the README.md.  The runtime seems to be looking for a message broker to be running, locally.  In my opinion, either this option should be off by default or an in-memory broker should be used for local execution.

**Command**
`mvn package wildfly:dev -f ui/pom.xml`

**Results**
```
[INFO] A server already exists in <project root redacted>/jakartaee/starter/ui/target/server, provisioning for org.eclipse.starter:jakarta-starter-ui
[INFO] JBoss Threads version 2.4.0.Final
[INFO] JBoss Remoting version 5.0.29.Final
[INFO] XNIO version 3.8.16.Final
[INFO] XNIO NIO Implementation Version 3.8.16.Final
[INFO] ELY00001: WildFly Elytron version 2.5.2.Final
[INFO] JAVA_HOME : /usr/local/Cellar/openjdk/23/libexec/openjdk.jdk/Contents/Home
[INFO] JBOSS_HOME: <project root redacted>/jakartaee/starter/ui/target/server
[INFO] JAVA_OPTS : -Xms64m -Xmx512m -Djava.net.preferIPv4Stack=true -Djava.awt.headless=true -Djboss.modules.system.pkgs=org.jboss.byteman --add-exports=java.base/sun.nio.ch=ALL-UNNAMED --add-exports=jdk.unsupported/sun.reflect=ALL-UNNAMED --add-exports=jdk.unsupported/sun.misc=ALL-UNNAMED --add-modules=java.se
[INFO] STANDALONE server is starting up.
11:17:25,016 INFO  [org.jboss.modules] (main) JBoss Modules version 2.0.2.Final
11:17:25,557 INFO  [org.jboss.msc] (main) JBoss MSC version 1.4.13.Final
11:17:25,566 INFO  [org.jboss.threads] (main) JBoss Threads version 2.4.0.Final
11:17:25,679 INFO  [org.jboss.as] (MSC service thread 1-2) WFLYSRV0049: WildFly Full 26.1.3.Final (WildFly Core 18.1.2.Final) starting
11:17:26,284 INFO  [org.wildfly.security] (ServerService Thread Pool -- 26) ELY00001: WildFly Elytron version 1.19.1.Final
11:17:26,784 INFO  [org.jboss.as.server] (Controller Boot Thread) WFLYSRV0039: Creating http management service using socket-binding (management-http)
11:17:26,799 INFO  [org.xnio] (MSC service thread 1-3) XNIO version 3.8.7.Final
11:17:26,811 INFO  [org.xnio.nio] (MSC service thread 1-3) XNIO NIO Implementation Version 3.8.7.Final
11:17:26,835 INFO  [org.jboss.as.clustering.infinispan] (ServerService Thread Pool -- 58) WFLYCLINF0001: Activating Infinispan subsystem.
11:17:26,835 INFO  [org.wildfly.extension.elytron.oidc._private] (ServerService Thread Pool -- 55) WFLYOIDC0001: Activating WildFly Elytron OIDC Subsystem
11:17:26,835 INFO  [org.wildfly.extension.health] (ServerService Thread Pool -- 56) WFLYHEALTH0001: Activating Base Health Subsystem
11:17:26,838 INFO  [org.jboss.as.jaxrs] (ServerService Thread Pool -- 60) WFLYRS0016: RESTEasy version 4.7.7.Final
11:17:26,850 INFO  [org.wildfly.extension.microprofile.config.smallrye] (ServerService Thread Pool -- 70) WFLYCONF0001: Activating MicroProfile Config Subsystem
11:17:26,850 INFO  [org.wildfly.iiop.openjdk] (ServerService Thread Pool -- 57) WFLYIIOP0001: Activating IIOP Subsystem
11:17:26,851 INFO  [org.wildfly.extension.microprofile.jwt.smallrye] (ServerService Thread Pool -- 71) WFLYJWT0001: Activating MicroProfile JWT Subsystem
11:17:26,853 INFO  [org.jboss.as.jsf] (ServerService Thread Pool -- 65) WFLYJSF0007: Activated the following Jakarta Server Faces Implementations: [main]
11:17:26,859 INFO  [org.wildfly.extension.io] (ServerService Thread Pool -- 59) WFLYIO001: Worker 'default' has auto-configured to 16 IO threads with 128 max task threads based on your 8 available processors
11:17:26,861 INFO  [org.jboss.as.naming] (ServerService Thread Pool -- 73) WFLYNAM0001: Activating Naming Subsystem
11:17:26,864 WARN  [org.jboss.as.txn] (ServerService Thread Pool -- 80) WFLYTX0013: The node-identifier attribute on the /subsystem=transactions is set to the default value. This is a danger for environments running multiple servers. Please make sure the attribute value is unique.
11:17:26,867 INFO  [org.wildfly.extension.microprofile.opentracing] (ServerService Thread Pool -- 72) WFLYTRACEXT0001: Activating MicroProfile OpenTracing Subsystem
11:17:26,874 INFO  [org.jboss.as.connector] (MSC service thread 1-8) WFLYJCA0009: Starting Jakarta Connectors Subsystem (WildFly/IronJacamar 1.5.3.Final)
11:17:26,875 INFO  [org.wildfly.extension.metrics] (ServerService Thread Pool -- 69) WFLYMETRICS0001: Activating Base Metrics Subsystem
11:17:26,877 INFO  [org.jboss.as.webservices] (ServerService Thread Pool -- 82) WFLYWS0002: Activating WebServices Extension
11:17:26,890 INFO  [org.jboss.as.connector.subsystems.datasources] (ServerService Thread Pool -- 47) WFLYJCA0004: Deploying JDBC-compliant driver class org.h2.Driver (version 1.4)
11:17:26,911 INFO  [org.jboss.as.connector.deployers.jdbc] (MSC service thread 1-3) WFLYJCA0018: Started Driver service with driver-name = h2
11:17:26,914 INFO  [org.jboss.remoting] (MSC service thread 1-4) JBoss Remoting version 5.0.25.Final
11:17:26,916 INFO  [org.jboss.as.naming] (MSC service thread 1-3) WFLYNAM0003: Starting Naming Service
11:17:26,917 INFO  [org.jboss.as.mail.extension] (MSC service thread 1-3) WFLYMAIL0001: Bound mail session [java:jboss/mail/Default]
11:17:26,921 WARN  [org.wildfly.extension.elytron] (MSC service thread 1-2) WFLYELY00023: KeyStore file '<project root redacted>/jakartaee/starter/ui/target/server/standalone/configuration/application.keystore' does not exist. Used blank.
11:17:26,940 WARN  [org.wildfly.extension.elytron] (MSC service thread 1-2) WFLYELY01084: KeyStore <project root redacted>/jakartaee/starter/ui/target/server/standalone/configuration/application.keystore not found, it will be auto generated on first use with a self-signed certificate for host localhost
11:17:26,961 INFO  [org.wildfly.extension.undertow] (MSC service thread 1-7) WFLYUT0003: Undertow 2.2.19.Final starting
11:17:26,976 ERROR [org.jboss.as.controller.management-operation] (ServerService Thread Pool -- 57) WFLYCTL0013: Operation ("add") failed - address: ([("subsystem" => "iiop-openjdk")]): java.lang.NoSuchMethodError: 'void sun.misc.Unsafe.ensureClassInitialized(java.lang.Class)'
	at javax.orb.api@8.1.7.Final//sun.corba.SharedSecrets.getJavaCorbaAccess(SharedSecrets.java:67)
	at javax.orb.api@8.1.7.Final//com.sun.corba.se.spi.orb.ORB$2.run(ORB.java:210)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:319)
	at javax.orb.api@8.1.7.Final//com.sun.corba.se.spi.orb.ORB.setupPresentationManager(ORB.java:198)
	at javax.orb.api@8.1.7.Final//com.sun.corba.se.spi.orb.ORB.access$000(ORB.java:103)
	at javax.orb.api@8.1.7.Final//com.sun.corba.se.spi.orb.ORB$Holder.<clinit>(ORB.java:175)
	at javax.orb.api@8.1.7.Final//com.sun.corba.se.spi.orb.ORB.getPresentationManager(ORB.java:261)
	at org.wildfly.iiop-openjdk@26.1.3.Final//org.wildfly.iiop.openjdk.IIOPSubsystemAdd.launchServices(IIOPSubsystemAdd.java:150)
	at org.wildfly.iiop-openjdk@26.1.3.Final//org.wildfly.iiop.openjdk.IIOPSubsystemAdd$1.execute(IIOPSubsystemAdd.java:112)
	at org.jboss.as.controller@18.1.2.Final//org.jboss.as.controller.AbstractOperationContext.executeStep(AbstractOperationContext.java:1045)
	at org.jboss.as.controller@18.1.2.Final//org.jboss.as.controller.AbstractOperationContext.processStages(AbstractOperationContext.java:777)
	at org.jboss.as.controller@18.1.2.Final//org.jboss.as.controller.AbstractOperationContext.executeOperation(AbstractOperationContext.java:466)
	at org.jboss.as.controller@18.1.2.Final//org.jboss.as.controller.ParallelBootOperationStepHandler$ParallelBootTask.run(ParallelBootOperationStepHandler.java:384)
	at org.jboss.threads@2.4.0.Final//org.jboss.threads.ContextClassLoaderSavingRunnable.run(ContextClassLoaderSavingRunnable.java:35)
	at org.jboss.threads@2.4.0.Final//org.jboss.threads.EnhancedQueueExecutor.safeRun(EnhancedQueueExecutor.java:1990)
	at org.jboss.threads@2.4.0.Final//org.jboss.threads.EnhancedQueueExecutor$ThreadBody.doRunTask(EnhancedQueueExecutor.java:1486)
	at org.jboss.threads@2.4.0.Final//org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1348)
	at java.base/java.lang.Thread.run(Thread.java:1575)
	at org.jboss.threads@2.4.0.Final//org.jboss.threads.JBossThread.run(JBossThread.java:513)

11:17:27,016 INFO  [org.jboss.as.ejb3] (MSC service thread 1-3) WFLYEJB0482: Strict pool mdb-strict-max-pool is using a max instance size of 32 (per class), which is derived from the number of CPUs on this host.
11:17:27,016 INFO  [org.jboss.as.ejb3] (MSC service thread 1-2) WFLYEJB0481: Strict pool slsb-strict-max-pool is using a max instance size of 128 (per class), which is derived from thread worker pool sizing.
11:17:27,045 INFO  [org.wildfly.extension.undertow] (ServerService Thread Pool -- 81) WFLYUT0014: Creating file handler for path '<project root redacted>/jakartaee/starter/ui/target/server/welcome-content' with options [directory-listing: 'false', follow-symlink: 'false', case-sensitive: 'true', safe-symlink-paths: '[]']
11:17:27,055 INFO  [org.wildfly.extension.undertow] (MSC service thread 1-2) WFLYUT0012: Started server default-server.
11:17:27,055 INFO  [org.wildfly.extension.undertow] (MSC service thread 1-5) Queuing requests.
11:17:27,057 INFO  [org.wildfly.extension.undertow] (MSC service thread 1-5) WFLYUT0018: Host default-host starting
11:17:27,128 INFO  [org.jboss.as.ejb3] (MSC service thread 1-3) WFLYEJB0493: Jakarta Enterprise Beans subsystem suspension complete
11:17:27,144 INFO  [org.wildfly.extension.undertow] (MSC service thread 1-7) WFLYUT0006: Undertow HTTP listener default listening on 127.0.0.1:8080
11:17:27,179 INFO  [org.wildfly.extension.undertow] (MSC service thread 1-7) WFLYUT0006: Undertow HTTPS listener https listening on 127.0.0.1:8443
11:17:27,181 INFO  [org.jboss.as.connector.subsystems.datasources] (MSC service thread 1-3) WFLYJCA0001: Bound data source [java:jboss/datasources/ExampleDS]
11:17:27,408 ERROR [org.jboss.as.controller.management-operation] (Controller Boot Thread) "WFLYCTL0193: Failed executing subsystem iiop-openjdk boot operations"
11:17:27,408 ERROR [org.jboss.as.controller.management-operation] (Controller Boot Thread) WFLYCTL0013: Operation ("parallel-subsystem-boot") failed - address: ([]) - failure description: "\"WFLYCTL0193: Failed executing subsystem iiop-openjdk boot operations\""
11:17:27,414 ERROR [org.jboss.as.controller.management-operation] (ServerService Thread Pool -- 68) WFLYCTL0190: Step handler org.jboss.as.controller.AbstractAddStepHandler$1@3264f529 for operation add at address [
    ("subsystem" => "messaging-activemq"),
    ("server" => "default"),
    ("security-setting" => "#"),
    ("role" => "guest")
] failed -- java.lang.IllegalStateException: java.lang.IllegalStateException
	at org.wildfly.extension.messaging-activemq//org.wildfly.extension.messaging.activemq.ActiveMQServerService.getValue(ActiveMQServerService.java:324)
	at org.wildfly.extension.messaging-activemq//org.wildfly.extension.messaging.activemq.ActiveMQServerService.getValue(ActiveMQServerService.java:78)
	at org.jboss.msc@1.4.13.Final//org.jboss.msc.service.ServiceControllerImpl.getValue(ServiceControllerImpl.java:1109)
	at org.jboss.msc@1.4.13.Final//org.jboss.msc.service.DelegatingServiceController.getValue(DelegatingServiceController.java:103)
	at org.wildfly.extension.messaging-activemq//org.wildfly.extension.messaging.activemq.SecurityRoleAdd.getServer(SecurityRoleAdd.java:84)
	at org.wildfly.extension.messaging-activemq//org.wildfly.extension.messaging.activemq.SecurityRoleAdd.rollbackRuntime(SecurityRoleAdd.java:74)
	at org.jboss.as.controller@18.1.2.Final//org.jboss.as.controller.AbstractAddStepHandler$1$1.handleRollback(AbstractAddStepHandler.java:169)
	at org.jboss.as.controller@18.1.2.Final//org.jboss.as.controller.AbstractOperationContext$RollbackDelegatingResultHandler.handleResult(AbstractOperationContext.java:1598)
	at org.jboss.as.controller@18.1.2.Final//org.jboss.as.controller.AbstractOperationContext$Step.invokeResultHandler(AbstractOperationContext.java:1570)
	at org.jboss.as.controller@18.1.2.Final//org.jboss.as.controller.AbstractOperationContext$Step.handleResult(AbstractOperationContext.java:1552)
	at org.jboss.as.controller@18.1.2.Final//org.jboss.as.controller.AbstractOperationContext$Step.finalizeInternal(AbstractOperationContext.java:1509)
	at org.jboss.as.controller@18.1.2.Final//org.jboss.as.controller.AbstractOperationContext$Step.finalizeStep(AbstractOperationContext.java:1492)
	at org.jboss.as.controller@18.1.2.Final//org.jboss.as.controller.AbstractOperationContext$Step.access$400(AbstractOperationContext.java:1356)
	at org.jboss.as.controller@18.1.2.Final//org.jboss.as.controller.AbstractOperationContext.executeResultHandlerPhase(AbstractOperationContext.java:910)
	at org.jboss.as.controller@18.1.2.Final//org.jboss.as.controller.AbstractOperationContext.executeDoneStage(AbstractOperationContext.java:896)
	at org.jboss.as.controller@18.1.2.Final//org.jboss.as.controller.AbstractOperationContext.processStages(AbstractOperationContext.java:803)
	at org.jboss.as.controller@18.1.2.Final//org.jboss.as.controller.AbstractOperationContext.executeOperation(AbstractOperationContext.java:466)
	at org.jboss.as.controller@18.1.2.Final//org.jboss.as.controller.ParallelBootOperationStepHandler$ParallelBootTask.run(ParallelBootOperationStepHandler.java:384)
	at org.jboss.threads@2.4.0.Final//org.jboss.threads.ContextClassLoaderSavingRunnable.run(ContextClassLoaderSavingRunnable.java:35)
	at org.jboss.threads@2.4.0.Final//org.jboss.threads.EnhancedQueueExecutor.safeRun(EnhancedQueueExecutor.java:1990)
	at org.jboss.threads@2.4.0.Final//org.jboss.threads.EnhancedQueueExecutor$ThreadBody.doRunTask(EnhancedQueueExecutor.java:1486)
	at org.jboss.threads@2.4.0.Final//org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1348)
	at java.base/java.lang.Thread.run(Thread.java:1575)
	at org.jboss.threads@2.4.0.Final//org.jboss.threads.JBossThread.run(JBossThread.java:513)

11:17:27,418 INFO  [org.jboss.as.mail.extension] (MSC service thread 1-7) WFLYMAIL0002: Unbound mail session [java:jboss/mail/Default]
11:17:27,419 INFO  [org.wildfly.extension.undertow] (MSC service thread 1-5) WFLYUT0019: Host default-host stopping
11:17:27,420 ERROR [org.jboss.as.controller.client] (ServerService Thread Pool -- 68) WFLYCTL0190: Step handler org.jboss.as.controller.AbstractAddStepHandler$1@3264f529 for operation add at address [
    ("subsystem" => "messaging-activemq"),
    ("server" => "default"),
    ("security-setting" => "#"),
    ("role" => "guest")
] failed -- java.lang.IllegalStateException
11:17:27,418 INFO  [org.jboss.as.connector.subsystems.datasources] (MSC service thread 1-1) WFLYJCA0010: Unbound data source [java:jboss/datasources/ExampleDS]
11:17:27,423 INFO  [org.wildfly.extension.undertow] (MSC service thread 1-2) WFLYUT0008: Undertow HTTPS listener https suspending
11:17:27,423 INFO  [org.wildfly.extension.undertow] (MSC service thread 1-2) WFLYUT0007: Undertow HTTPS listener https stopped, was bound to 127.0.0.1:8443
11:17:27,428 INFO  [org.wildfly.extension.undertow] (MSC service thread 1-7) WFLYUT0008: Undertow HTTP listener default suspending
11:17:27,428 INFO  [org.wildfly.extension.undertow] (MSC service thread 1-7) WFLYUT0007: Undertow HTTP listener default stopped, was bound to 127.0.0.1:8080
11:17:27,429 INFO  [org.jboss.as.connector.deployers.jdbc] (MSC service thread 1-2) WFLYJCA0019: Stopped Driver service with driver-name = h2
11:17:27,433 INFO  [org.wildfly.extension.undertow] (MSC service thread 1-3) WFLYUT0004: Undertow 2.2.19.Final stopping
11:17:27,451 FATAL [org.jboss.as.server] (Controller Boot Thread) WFLYSRV0056: Server boot has failed in an unrecoverable manner; exiting. See previous messages for details. - Server configuration file in use: standalone-full.xml
11:17:27,461 INFO  [org.jboss.as] (MSC service thread 1-5) WFLYSRV0050: WildFly Full 26.1.3.Final (WildFly Core 18.1.2.Final) stopped in 6ms
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  9.144 s
[INFO] Finished at: 2024-10-02T11:17:27-04:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.wildfly.plugins:wildfly-maven-plugin:5.0.1.Final:dev (default-cli) on project jakarta-starter-ui: The server failed to start: The process 66085 is no longer active. -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
```

**Comment by qdubious** [comment]
@m-reza-rahman  - Ah, that was it.  The UI app started up with JDK 17.
