### ISSUE TITLE
payara-micro command fails on binding address on Mac M1

### ISSUE THREAD

**Issue by IvoNet** [eclipse-ee4j/starter#99]
I've tried the 1.0.0 archetype as described on https://start.jakarta.ee/ and it fails on my MacbookPro M1 (aarch64) with the following error:

```shell
[2022-04-20T20:37:18.986+0200] [] [SEVERE] [] [com.hazelcast.instance.impl.Node] [tid: _ThreadID=24 _ThreadName=RunLevelControllerThread-1650479838464] [timeMillis: 1650479838986] [levelValue: 1000] [[
  [fe80:0:0:0:d0a7:2bff:fe4b:9e9e]:6900 [development] [4.2] Can't assign requested address
java.net.BindException: Can't assign requested address
	at java.base/sun.nio.ch.Net.joinOrDrop6(Native Method)
	at java.base/sun.nio.ch.Net.join6(Net.java:741)
	at java.base/sun.nio.ch.DatagramChannelImpl.innerJoin(DatagramChannelImpl.java:1523)
	at java.base/sun.nio.ch.DatagramChannelImpl.join(DatagramChannelImpl.java:1559)
	at java.base/sun.nio.ch.DatagramSocketAdaptor.joinGroup(DatagramSocketAdaptor.java:535)
	at java.base/sun.nio.ch.DatagramSocketAdaptor.joinGroup(DatagramSocketAdaptor.java:481)
	at java.base/java.net.MulticastSocket.joinGroup(MulticastSocket.java:325)
	at com.hazelcast.internal.cluster.impl.MulticastService.createMulticastService(MulticastService.java:142)
	at com.hazelcast.instance.impl.Node.<init>(Node.java:274)
	at com.hazelcast.instance.impl.HazelcastInstanceImpl.createNode(HazelcastInstanceImpl.java:148)
	at com.hazelcast.instance.impl.HazelcastInstanceImpl.<init>(HazelcastInstanceImpl.java:117)
	at com.hazelcast.instance.impl.HazelcastInstanceFactory.constructHazelcastInstance(HazelcastInstanceFactory.java:211)
	at com.hazelcast.instance.impl.HazelcastInstanceFactory.newHazelcastInstance(HazelcastInstanceFactory.java:190)
	at com.hazelcast.instance.impl.HazelcastInstanceFactory.newHazelcastInstance(HazelcastInstanceFactory.java:128)
	at com.hazelcast.core.Hazelcast.newHazelcastInstance(Hazelcast.java:57)
	at fish.payara.nucleus.hazelcast.HazelcastCore.bootstrapHazelcast(HazelcastCore.java:504)
	at fish.payara.nucleus.hazelcast.HazelcastCore.getInstance(HazelcastCore.java:239)
	at fish.payara.nucleus.config.ClusteredConfig.postConstruct(ClusteredConfig.java:100)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.glassfish.hk2.utilities.reflection.ReflectionHelper.invoke(ReflectionHelper.java:1268)
	at org.jvnet.hk2.internal.ClazzCreator.postConstructMe(ClazzCreator.java:309)
	at org.jvnet.hk2.internal.ClazzCreator.create(ClazzCreator.java:351)
	at org.jvnet.hk2.internal.SystemDescriptor.create(SystemDescriptor.java:463)
	at org.glassfish.hk2.runlevel.internal.AsyncRunLevelContext.findOrCreate(AsyncRunLevelContext.java:281)
	at org.glassfish.hk2.runlevel.RunLevelContext.findOrCreate(RunLevelContext.java:65)
	at org.jvnet.hk2.internal.Utilities.createService(Utilities.java:2102)
	at org.jvnet.hk2.internal.ServiceHandleImpl.getService(ServiceHandleImpl.java:93)
	at org.jvnet.hk2.internal.ServiceLocatorImpl.getService(ServiceLocatorImpl.java:680)
	at org.jvnet.hk2.internal.ThreeThirtyResolver.resolve(ThreeThirtyResolver.java:54)
	at org.jvnet.hk2.internal.ClazzCreator.resolve(ClazzCreator.java:188)
	at org.jvnet.hk2.internal.ClazzCreator.resolveAllDependencies(ClazzCreator.java:211)
	at org.jvnet.hk2.internal.ClazzCreator.create(ClazzCreator.java:334)
	at org.jvnet.hk2.internal.SystemDescriptor.create(SystemDescriptor.java:463)
	at org.glassfish.hk2.runlevel.internal.AsyncRunLevelContext.findOrCreate(AsyncRunLevelContext.java:281)
	at org.glassfish.hk2.runlevel.RunLevelContext.findOrCreate(RunLevelContext.java:65)
	at org.jvnet.hk2.internal.Utilities.createService(Utilities.java:2102)
	at org.jvnet.hk2.internal.ServiceHandleImpl.getService(ServiceHandleImpl.java:93)
	at org.jvnet.hk2.internal.ServiceHandleImpl.getService(ServiceHandleImpl.java:67)
	at org.glassfish.hk2.runlevel.internal.CurrentTaskFuture$QueueRunner.oneJob(CurrentTaskFuture.java:1213)
	at org.glassfish.hk2.runlevel.internal.CurrentTaskFuture$QueueRunner.run(CurrentTaskFuture.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
]]
```
Full stack trace here:
[stacktrace.txt](https://github.com/eclipse-ee4j/starter/files/8524510/stacktrace.txt)

Just to be sure I asked a friend with the same M1 Laptop and it also fails for him.
When I run it from within a standard java enabled docker container it all works.

I also tried it on the 1.1.0-SNAPSHOT and the same happens

**Comment by m-reza-rahman** [comment]
This is a known issue with M1 support in Payara. TomEE and GlassFish should work fine. Do you feel this is an important enough issue to document prominently? If so, I will issue a PR documenting it.

**Comment by IvoNet** [comment]
Might be nice to have a comment there with a workaround for now but I now realize I should have created this issue at payara. Still, a mention might help those searching why.

**Comment by m-reza-rahman** [comment]
OK. I’ll issue the PR. Do you have a workaround in mind? As far as I am aware, there isn’t one currently?

**Comment by IvoNet** [comment]
Will I've used it with my own docker [image](https://hub.docker.com/r/ivonet/payara) with the following command:

```shell
mkdir artifact
mvn clean package
cp target/*.war ./artifact
docker run -it --rm --name cafe -v $(pwd)/artifact:/opt/payara/payara5/glassfish/domains/domain1/autodeploy -p 8080:8080 -p 4848:4848 ivonet/payara:5.2022.1-jdk17
```

it runs just fine and every time you build anew you only have to copy the war to the artifact folder to redeploy during development.

Don't know if this is a valid workaround though.

**Comment by m-reza-rahman** [comment]
I agree we should not be in the business of trying to replace the official image. I will issue a PR simply noting the issue. I hope that is OK.
